[project]
name = "customer-support-env"
version = "0.1.0"
description = "Customer Support RL Environment for OpenEnv"
authors = [
    { name = "Prasanna Lakshmi Nandeti"},
    { name= "Pujitha Bollina" }
]
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "openai",
    "requests",
    "openenv-core"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"